language: node_js
file: dist/
node_js:
- stable
node_js:
- "6"
cache:
  directories:
    - "node_modules"
install:
- npm install
script:
- npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAXUFQQYVW7TGM22NM
  secret_access_key:
    secure: "uo2QAkBg1c/ntlxxKfLr5GAmlrgECzheNvzPflr9zfbjivn72qyS2+G7uKcq1+7+XsyxjhG2owkKemjFZqWGs38T8BsXEWDcmmMe9Bca5OmNkx78vz6qYKX5CBnpIxwzTSInxKZ0teBCqTV4zS069zUVdYxGnbncxFxV9YElpFv90mVL0B4ACG37skf5Y84eFY8XUHuM/r37cwwBOd6o8vJ7S1U/dSxQTBTFCvzwEPDKYQGMXNCrudnm+x9S3tgLfG3giM2r7eRSjjVyEGt9Yvz0ZW+Qd8bk0SFu9egj4sDcHFwdq5oJWIOyd7Mq07jro0Xn4O65djEFRRZEOSUdElO13YrVNCCylHAg/44qVEWLW6j7XStsAMGSrW7VgxYAIyH0TLOOJ8uJ6wpo+Eko9r68LarmQEZSy3EP3RmFOS9+p8kaiCQoVUM4+6riof0XRZfL6/FaQyrwQ6bjrqRjn84g64Ik9DKd259LZ7JA7/cLXL0uGCevnUrdjqBMr9bNQ3ui7hUFA7XN5PNqVGA9Wr5bImi2HAfmAyGxeRJ4tH4xtSMiFmvH3bDU0SYbbX1Hhgxl7mcMVrjc1DxlWQc3i5y8F392CG5jMPgMbyXdrgrrq5cZDXSFEZbSDfmG4kodOiCr1ve2KrVKhK+uBFGqFewXrzZhYWr6XlJNwr1T43w="
  region: "us-east-1"  
  app: "dynamoc"
  env: "Dynamoc-env"
  bucket_name: elasticbeanstalk-us-east-1-524356207981
