language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAXUFQQYVW5FKPLO5G
  secret_access_key:
    secure: qtS7v/NpjgZxBwY1Kyqh9NRuTl6R+bHIWtRqwqcYp7NEPGJ3iuIb1+W39Kqba2+Vu+mVrhOCsd2C3j6S+HCW7Ci/TCKzePrE540h4gj5bM/vD2phqfgJ6CK1l+YNr9AKHSskSLO1UgAmWTTh+yLNtgKnwEMp9Q0ETu5RDJpuO5Nw7NMLXJsPMxHXmpxTAYD4Jwc6kqD53rJdnI82TtNCkfuFaeQL9CWzAFAensbNxVE16Rq8QGu/k7HasIrE6yua2whdE59MXL0vmxQpEd44XFZoRWIyemFZs1Kc1DRKJ+gT9/dl1w9o166ehq8Bg5VWnFAGDb1u9XVBR3+2G256igm7NVqqEcy4D5WtcgeKdp2BCGtylrL8dHxPLQ8Vg2PwhAX6guynULNwZKQGMZGrhmmsv81jXT5Wk8YNpfX5YMlKtxzg7nUpkV3HPIT73hObh6Z7c+QgWPVwq0XoaSen+OHQ9ms6PzXXJ6LmnrLq8VUkB1FCGkaRW2/6cbEbw/h2+puWQbHuTDBrMAmja6rYY5rJGLM0RhM37v9JAgadERpHcnzp7eao76OYj5fe/BQCY0uwgPGe6MydNWI74Chwr4+uTYeB+u8g+4LQViZsvXH0glroFPx3HVIOsPPeOv2KqMsbwvNDSw3cvwzXK7YFq7KyFbZDJFCYMz/EhWaqRds=
  bucket: dynamoc
  region: us-east-1
  local_dir: dist
