language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAXUFQQYVW5FKPLO5G
  secret_access_key: ${SECRET_ACCESS_KEY}
  bucket: dynamoc
  region: us-east-1
  local_dir: dist
