language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAXUFQQYVW5FKPLO5G
  secret_access_key:
    secure: cbBygUe/jgGmYsuKrPS3ytyK6VUuNBxqabmG6qe5yaU0UF2GIcUsI5uB947sRUW64IQes+Sm1E/peqGex7/HGu78cVhZwWqghCQQeujiWooTYySFdLqslUajW6B2GtQ7/6EO8cv98bIbjWYcsv97YyL7H9IyKkdcUNnL8Qd04zRGFKlVVA0CBqCWqAuJS259kWEWV6qbLHXbxP2FOnR5cr7MpVGa9AhxjLKzJJkPr8zBEZzh6DEePy6NxxlvU/ziG8AFdFvQ7n7MSAz2amFnIenVNWOHrD5nmlxR0E0HXQLs8TYZ4XTY4YAUrBj4kOGSjUGPuz2XR7iop7mLO9eattUgydcuA8OiIlaPTO+gNURa15NHl9kF1neb27IfgDAQjuYlXRTbhEh8RFkR+RaPD3qNdo00lLS6tVvrbSW95kcgN+ktVTmbSMZqKbEnj0C8CWnu9paa1HJSAwiYI/b54cE516kGhpXGxkDMpWgpaLtwKyVQT6f0/9Rljb96rv1E2twMdNIvVIlOPmFoFqGcqA/gGxm5Nuep3tHS5gkWaeGtXjFmzE4Tvs2ADyvrCyhYQlZAwICfgUepSzmbg7G/X3NCeeOeKBshTEjimAINqX3oQiqIKLfjkmBGrTkQXBI9flty+JQ7jgjo/HkNoh6FRjAqlT4RrYEX/+7F3FpaN5k=
  bucket: dynamoc
  region: us-east-1
  local_dir: dist
