language: node_js
file: dist/
node_js:
- stable
node_js:
- "6"
cache:
  directories:
    - "node_modules"
install:
- npm install
script:
- npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "QyJKYMvGI/mUjF7Dk/iwCKljWgUvexlkaSH6b0aEZJFy8BzOXm+EspQNDkwraHQXrGub8ftZn0qA2kMkC5nmb3T2BvJ6sGjtqNhthW83sWcSG3ZFKmu7pDeAKiGRphUT5nsUUS1Np0FIm9qHw/hzAvhTPPb9JcatNhXRfR2CzBBv+5vdt+MXaqS6RdlnW+jnrgkXg0LbSCyMAiX/qySFbj3zMIg4vF7zXJLKADdWaev9X0qRrXYTgkbdsEEhsz0urpEJKRcsvvoceb9N8kao+tm36NpKAdiEgT3cVHJlCxHDRuygK4FOWXjay+WSLBF+CzXr38HRUH3m2pqtgkzvveESUcCjx9URJ3cagDEi3ZNzihWmj2P15WyKOU1ZIwXjOe42fYD46zvJyDmeC2kJV28Cp8hltLIUVNMd/xBn7RqxaZaAKHCeIH5RbApyLvJzOxpAcpRBNtgoIhndt1DVHhzjU6LOIKkjqJsqvdCAgimNCgKrK464jopaIc3+QcQyCrq8zEAm2EySxn61PPOYsJrBWwWsqUlHe8P7QSfgWNWYrvArVfnp6Kq3OUXT/xM0xZobKZ2OK3oQ8cgvNdnDTz+9HsXT3KOWkA2lWyrwOGcdOguo7+i4jJ29yl/3aPDVM0NtrmG12tB6wsqSbigyLdsQhInZuByHCYdCKooRMS8="
  secret_access_key:
    secure: moYQl0I+50AOFCz5S6T/TyrcAdzf7zf05SK+k9WBCVlnAY+OGjEBE8MwA7+bE9AZJoOtljVXc87kPHlCN8bPYJqwESUYgKGWmY4Nh5B+D8RjcGOvUX/fILSRfharaod0VM/sikvxDYRjvdYHp8GtYLpkBPV/yOFJg7HJ/pGEVSRW5hA0t3h2tW8LRH+q4WOHkoau+sq9UQ4o4qYWDJBrOZEsmJQcwH8fDTd4HzSr2XEMSP0uV2momHtvQZFfuIaVtIs1O4u2tY1i+2uU1/eI7rYcPmxZlNbDH889zOQZXCI2dflMky4rR6xZFjylgpkq5XXK00EQ3h+/JmA4ChXwnKP3Tn13WJeIEPfGxD4GyrV8PJvEiDUR0TejRijnBgerAiI4I83AFml5kFN7foruY2JaPqm76Lz0iG+jTzCwZeSMRGLw/G/CvNP6arZlEsckEZTKXdD+Yp5SNz/o6Aq850EQeEMJIhHWeozpnbkg5CF/K9cLS1d3h+OSzeaAT2l/4p63MwabDOnjKEbHM0ZFGIL6wc6fuAatkQK4khRaLKdBnEyzNKcCPqzlBoyP2X/yTlb6/V7LenO0tfZ8kQspci2+uNVAZ5k5pFmt7VBY2KiX8VxA0+68qy3PQsYHomTGlwUnNDjPoPhXske3SP/+i/smBGhu78OHUSFg6KL2Cnk=
  region: us-east-1
  app: meetup-sample
  env: MeetupSample-env
  bucket_name: elasticbeanstalk-us-east-1-732770059798
