language: node_js
file: dist/
node_js:
- stable
node_js:
- "6"
cache:
  directories:
    - "node_modules"
install:
- npm install
script:
- npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "nOO8aH7jl2FcAOWdomWR8j7TRcTW8q9Yu7N18eXKJeoo2BmAheEoEzwG54p3HZ52UkrR9IaXXmW+0igid35at5Bja2gPmI/RnXOI79Q07nQ4zsrl46V1n6zEhaZgoQiB9BMpAcDPyfx2tbOX8inI520SkCfzjkrZGpC2fg31z4As4bdtHgvpSN2lNLG1hZl68jifCU8ZsSG7JbnzTLhiFn/Ind+F6Z36Ht7zwTUtIp8FyJOh7vcZhnVihRzAacTKPmDQbSlfleNBucJhYt3xDWDao6kfV98WqE9HAFjfaZh1XHw83S1DoEcULKCIm2YRNCqZlAAhUqYSJKY5pPfcs8dRupSR0Hv57tGXIkOFXzy2AQkVuYCu+Ef6SPspPjbypxa8trBFMFOY6/eng1jQlbgOadJcU+rvMDPGLFxyruoqDQ6KtK+Io9++B5M0Mu1g8gZntIXtqCLEEiSeRzVN8vIBWaDyecorF31esWxfMenW6f/vG5xeWzwpXHFpuRrHmt09RpbyXHZwPvUlInYCyh8KLt/VwbIXhmxvN4g0Nk/EO0sCuv/8KAW/48uQ79eJ/auTYIkIu+E1IJN+iwpKcJSHihvrUyyRm1sZft72+Djl23EYD3QNkFjTQvBkm0bRoX1clefrrQborxFqTTl0eu2Tc4cVTpIbjtVg2WZaA0g="
  secret_access_key:
    secure: "mCOeiE/nKq1vBHyYaRxed5B0BmlgjR3FVJNMuTPvyyM5SmzgjgeWrwKgvypMZ8vFVJYBNhVqMaFnoaY6hY5AXEEV1/USzeCr+zyV4G6tO2ldzNkm35zpYLj0DSMJhb1+GYYE83tNUzE/eTIUOrBqQWHwRkX4BdcUiJGUjTw3RFaZ5VeoRnMAudJQo8VDZMGPlypis6DRnnS0Y9yphvw97GSFXi97W7Fjp0RZFX4N/PHuSN1wQT7OPIsFPw1KwekdAcD/yqUfEiyLCLUPH49Bez4Uth6n+NmVlfIo/BoMQJukH7nsEDIERBd4UdrElzDciRE7QYfPqIquaHOEaxqsp4zeGcxXgnugu8G43/CUCpAmG0wBouWas8X5gU1Gb+wb3+UdTf/4X03jX3mlF0SJOLjDmYTbtKWE035IUUqIGt+QHFz1SOuSFAuJq82deSqwCs9HuspIqrmbaoO+mlcjIECD26ftWPJnnKcxgHp/7bVfxuic47/2wyt5IYoQNIon9NwOIaiLmF9sF34bo0RRgHp8/qh0q9Ou+O7IGqQiPLVCn7KyFzOm3ywTy1tTzv7TU7JuSKBdjMQGwVoHSwjlC0nuVyAf3nx66g7gprDePw/qjorsOPh9PGUpJ7k2+teNlVOf5mhk8vNqixIjVVFCP/T3Kal/uhnXnSyxx3Paeuc="
  region: "us-east-1"  
  app: "dynamoc"
  env: "dynamoc-environment"
  bucket_name: "dynamoc-bucket"

