language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAXUFQQYVW5FKPLO5G
  secret_access_key:
    secure: c0epmhIPt12YlviHeYpwABaFUaRfomxXwgFzUTdL22Tmzk+6t6CfAIHqj+lm/rM4ymDT8V6urve1GOiP2uKS8ajWUG7cpWi+04F8PMGsmAiyL2SGhh/cS6m/cUVaPP3WQ3SJzgw1K0fJjWtvFaQugJrrsFfJQI05qjkYGiWjg7SCHdfkAYxvRBt0z4YrgQ0H2He0WJSIOy9RpQps2PbJI7Em2nCCnh4zx1N5M/YKvk/k/tyrzXjOJUPw8kCYX5CEJQ+O2I26lQZR7Q9JiUnLopoiZIdewiD1UyhK6Vzl99yQl2IRuZuMjebSTGaMrynWsuuoCsMxqC3IGAeS54kXxK1zrl5J6aPtwlh3lcYTqNv2+amF/SANFFCoggLadO4ect5i3Hm2bbW8zyIKkYt9JZmdfHEkuWJs1OyAG1V5FQcerqRGm/0BjRGTM10Iin10QZjW8eNaEXYyuHEOGcaVxaxtUO2X1NJc9UMBVzZjmsR37Nl418xJFsDdEMQzlTRNyc4d1Do/P1z2xi5vzv7hP9sJBA8BoQ1k7uYCFqyC+XajpnA5eUe5T9liQ39hyX8ZqHzIOUiDry+1IqknE+c20XMuBbl95vEYwVcaN6lkjTX369KOg6FPUJs2oaM+oMU0G4cihhVkISbQiXi79U3qBQzBhdusTnAXGTG/EYmPnLA=
  bucket: dynamoc
  region: us-east-1
  local_dir: dist
