language: node_js
file: dist/
node_js:
- stable
node_js:
- "6"
cache:
  directories:
    - "node_modules"
install:
- npm install
script:
- npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAXUFQQYVW5KSSXCD7"
  secret_access_key: "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"
  region: "us-east-1"  
  app: "dynamoc"
  env: "dynamoc-environment"
  bucket_name: "dynamoc-bucket"

