language: node_js
node_js:
- stable
node_js:
- "6"
cache:
  directories:
    - "node_modules"
install:
- npm install
script:
- npm run build
deploy:
  provider: azure_web_apps
  username: "ieiayaobb@outlook.com"
  password: "BE4@gN6RMdH*@iYpHmJD"
  site: "Dynamoc"
