language: node_js
file: dist/
node_js:
- stable
node_js:
- "6"
cache:
  directories:
    - "node_modules"
install:
- npm install
script:
- npm run build
deploy:
  provider: azure_web_apps
  verbose: true

