language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAXUFQQYVW5FKPLO5G
  secret_access_key:
    secure: RTH6NuV/40OsM2lVhRqBJl5Man70CeCBLPh6rCKx4LVuOOsAXQBdqhBRr8//P5XYnkplKlVUkfktWWeI2Dchyyzego6x0YwabFhs8pqlGmkwN3dfENOighPW/G4LgqMkjRrqgXxh9DlCctueTazN2DanUWUWmcdM63AGZqTyieBNMDmnvxClnKMyNBvCvXKlwDgHLaMuVshBLv+SE0IUDNaaSsXBbVkCwrImoffBoUbthjAQI4oG7JNBCn2LWKWsSK9LIIK84s363VO31Rew2R8RrjcF7BQCBRTfEndO9eBe68WBXdMN0ETKytrVPiFBLh76j7NM9F0Fy3TXyDM+n8v1vRLbjbbWOVZuyYdxeOE2NdyFHoWIpvndoELHP9cp4f/9ne6lJXcdP+2AeFeASgTMb1WSsq5zwaqNhlUTQ1ykNj/Ihs95xKL2dE2CQ7+EkAo7FOY7OZBtIM010PNNIw7wDg7+Aqy4slDOM+xXQI5W4PwfI+CMQ4CYYvYorDnFKVs0wdFAZbCjJ3nA+gPrj9RClP0RW2mymQg9voqBexvBY8jQgz5vU4ntECZ+0DcFLpmWZdVd5VZqzTChbLu2+AMqJayFKTMebk+2xNRLXYcOHK2eDtJvFdieWBJKDNjYNfPiq0hjrC4oTAwnVeRDCjIh/i+DePgKcm1EUQnX+20=
  bucket: dynamoc
  region: us-east-1
  local_dir: dist
