language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAXUFQQYVW5FKPLO5G
  secret_access_key:
    secure: jj9l450XJAztIEABph/Cf12BYFahWPCanmMiIlPpD8auHjTAuPICL7zaZqtPNz3QxAjpRsfGLxTOw7qotPKW5RrpwoNnsfnjjWHCCssVYzQ6CFuKtyHRXonAMbk1cAiqXwTRGl5P4fP2dMOF1NulvMEFzmtr01hRR519ziybl4tAy+DdJtIBLMWkLHYXm8odCK1Ok1ImBwRWlUi3KFmCobLCuJ81uhX64gZd7LAPuUnVvokwrR/K7rtS1KJQBt1dTggIAHMlRRcNiG1Mvdzrp7ZP0aZLuK9CN0yB96bVdu5sU+eZPDN+bWzcLUYojplPESg91hC5nr8MqqZvhBbi3ivyPh7Pldozr9OzGaqH/hVdUuNmXGGozmnS1iDhLBOXI4zRL8gu2iVSgmjGKPIKAQAXdcvbk+JHaesdwuCctykC8zBPpB4OOMaOPGNIXgNS21iEptjh3fLoJhYU4TdHvid8CogToAoBcROABAkBqSU5kq1SyXE2g+xo1nllc+euTFwnmQJh2MVgw/dNZkeCDnYnIEM07aG/cUAN/9+beQzkjfJ1ZwEb0OqljDalVYwN4eZzjZ07MmdDX8lKFy4BJafb2s6SZ3Fno/yoDdK7svIqN6xIV4/jDnCty4ZD5w4kzj5X8tuMrnNB29hlgcdOvMisFwfrrUJOI82aO/ICyWA=
  bucket: dynamoc
  region: us-east-1
  local_dir: dist
